teacher_list = [
    {'code': '1.1', 'teachers': ["ANNA KARYNE TURBAY PALODETTO"], 'cohorts': 'DEL'},
    {'code': '1.1', 'teachers': ["ANNA KARYNE TURBAY PALODETTO"], 'cohorts': 'APJ04'},
    {'code': '1.1', 'teachers': ["SILAS ROQUE DOS SANTOS"], 'cohorts': 'APJ05'},
    {'code': '1.1', 'teachers': ["SILAS ROQUE DOS SANTOS"], 'cohorts': 'APJ06'},
    {'code': '1.1P', 'teachers': ["VINICIUS AUGUSTUS DE CARVALHO"], 'cohorts': 'PAP'},
    {'code': '1.2', 'teachers': ["JOŚE BARRETO DE MACEDO JUNIOR"], 'cohorts': 'DEL+APJ'}, 
    {'code': '1.2P', 'teachers': ["JOŚE BARRETO DE MACEDO JUNIOR"], 'cohorts': 'PAP'},   
    {'code': '1.3', 'teachers': ["ANDRE GUSTAVO FELTES"], 'cohorts': 'DEL+APJ'},
    {'code': '1.3P', 'teachers': ["MARCELO MAGALHÃES PEREIRA"], 'cohorts': 'PAP'},
    {'code': '1.4', 'teachers': ["ANA CRISTINA FERREIRA"], 'cohorts': 'DEL'},
    {'code': '1.4', 'teachers': ["ANA CRISTINA FERREIRA"], 'cohorts': 'APJ04'},
    {'code': '1.4P', 'teachers': ["RAFAEL LUCAS PIRES"], 'cohorts': 'APJ05'},
    {'code': '1.4P', 'teachers': ["MARIEL STÉDILE TORRES"], 'cohorts': 'APJ06'},
    {'code': '1.4P', 'teachers': ["MARILENE CONSTANTINO"], 'cohorts': 'PAP'},
    {'code': '1.5', 'teachers': ["ADRIANO PEREIRA ADURA"], 'cohorts': 'DEL+APJ'},
    {'code': '1.5P', 'teachers': ["ADRIANO PEREIRA ADURA"], 'cohorts': 'PAP'},
    {'code': '1.6', 'teachers': ["LEANDRO FARNESE TEIXEIRA"], 'cohorts': 'DEL'},
    {'code': '1.6', 'teachers': ["LEANDRO FARNESE TEIXEIRA"], 'cohorts': 'APJ04'},
    {'code': '1.6', 'teachers': ["RAFAEL BACELAR DE SOUZA"], 'cohorts': 'APJ05'},
    {'code': '1.6', 'teachers': ["RAFAEL BACELAR DE SOUZA"], 'cohorts': 'APJ06'},  
    {'code': '1.7', 'teachers': ["ALESSANDRO ROBERTO LUZ"], 'cohorts': 'DEL+APJ'},
    {'code': '1.9', 'teachers': ["ANNA KARYNE TURBAY PALODETTO"], 'cohorts': 'DEL'},
    {'code': '1.9', 'teachers': ["ANNA KARYNE TURBAY PALODETTO"], 'cohorts': 'APJ04'},
    {'code': '1.9', 'teachers': ["FERNANDO ZAMONER"], 'cohorts': 'APJ05'},
    {'code': '1.9', 'teachers': ["FERNANDO ZAMONER"], 'cohorts': 'APJ06'},
    {'code': '1.9P', 'teachers': ["FERNANDO ZAMONER"], 'cohorts': 'PAP'},
    {'code': '1.10', 'teachers': ["EDUARDO BERGMANN MOURA"], 'cohorts': 'DEL+APJ'},
    {'code': '1.11', 'teachers': ["ADRIANO CHOHFI"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '1.12', 'teachers': ["THAYSE CAMPOS MILESKI"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '1.13', 'teachers': ["ROSANA CLAUDIA BOTELHO"], 'cohorts': 'DEL'},
    {'code': '1.13', 'teachers': ["GIORGLLI SOARES PAIN"], 'cohorts': 'APJ04'},
    {'code': '1.13', 'teachers': ["GIORGLLI SOARES PAIN"], 'cohorts': 'APJ05'},
    {'code': '1.13', 'teachers': ["DANIEL LUIZ GODOY DALACQUA"], 'cohorts': 'APJ06'},
    {'code': '1.14', 'teachers': ["LUIZ RAFAEL JUNTA FERRO"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '1.15', 'teachers': ["CARLOS EDUARDO DE ARRUDA SILVEIRA"], 'cohorts': 'DEL+APJ'},
    {'code': '1.16', 'teachers': ["LUIZ RODRIGO GROCHOCKI"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '1.17', 'teachers': ["FLAVIO ADRIANO BALAN"], 'cohorts': 'DEL+APJ'},
    {'code': '1.18', 'teachers': ["ADRIANO PEREIRA ADURA"], 'cohorts': 'DEL'},
    {'code': '1.18', 'teachers': ["ADRIANO PEREIRA ADURA"], 'cohorts': 'APJ04'},
    {'code': '1.18', 'teachers': ["PAULO MURILO DIAZ BORGES"], 'cohorts': 'APJ05'},
    {'code': '1.18', 'teachers': ["PAULO MURILO DIAZ BORGES"], 'cohorts': 'APJ06'},
    {'code': '1.11P', 'teachers': ["ANA FLÁVIA FRIZZO"], 'cohorts': 'PAP'},
    {'code': '1.12P', 'teachers': ["ANA FLÁVIA FRIZZO"], 'cohorts': 'PAP'},
    {'code': '1.13P', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '1.14P', 'teachers': ["ALLAN SIMAS DE ALBUQUERQUE"], 'cohorts': 'PAP'},
    {'code': '1.15P', 'teachers': ["JULIANA L. ZEIDAN"], 'cohorts': 'PAP'},
    {'code': '1.16P', 'teachers': ["RODRIGO BERTUOL"], 'cohorts': 'PAP'},
    {'code': '1.17P', 'teachers': ["JULIANA VILELA DE BARROS"], 'cohorts': 'PAP'},
    {'code': '1.18P', 'teachers': ["JULIANA VILELA DE BARROS"], 'cohorts': 'PAP'},
    {'code': '1.19P', 'teachers': ["ALINE FRIZZO"], 'cohorts': 'PAP'},
    {'code': '1.20P', 'teachers': ["KAROL KASUKO FRAGOSO"], 'cohorts': 'PAP'},
    {'code': '1.21P', 'teachers': ["EDUARDO CEZAR SANTOS"], 'cohorts': 'PAP'},
    {'code': '1.22P', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '1.23P', 'teachers': ["AMANDA RODRIGUES DE MELLO"], 'cohorts': 'PAP'},
    {'code': '1.24P', 'teachers': ["ELENICE BUNICK DE BRITO"], 'cohorts': 'PAP'},
    {'code': '1.25P', 'teachers': ["AMANDA RODRIGUES DE MELLO"], 'cohorts': 'PAP'},
    {'code': '2.1', 'teachers': ["SANDRA MARA NEPOMUCENO"], 'cohorts': 'DEL+APJ'},
    {'code': '2.2', 'teachers': ["ANNA KARYNE TURBAY PALODETTO"], 'cohorts': 'DEL+APJ'},
    {'code': '2.3', 'teachers': ["SILAS ROQUE DOS SANTOS"], 'cohorts': 'DEL'},
    {'code': '2.3', 'teachers': ["SILAS ROQUE DOS SANTOS"], 'cohorts': 'APJ04'},
    {'code': '2.3', 'teachers': ["GERSON FAUSTINO"], 'cohorts': 'APJ05'},
    {'code': '2.3', 'teachers': ["GERSON FAUSTINO"], 'cohorts': 'APJ06'},
    {'code': '2.4', 'teachers': ["CLAUDIO MARQUES"], 'cohorts': 'APJ04'},
    {'code': '2.4', 'teachers': ["CLAUDIO MARQUES"], 'cohorts': 'PAP'},
    {'code': '2.4', 'teachers': ["CLAUDIO MARQUES"], 'cohorts': 'DEL'},
    {'code': '2.4', 'teachers': ["PAULA BRISOLA"], 'cohorts': 'APJ05'},
    {'code': '2.4', 'teachers': ["PAULA BRISOLA"], 'cohorts': 'APJ06'},
    {'code': '2.5', 'teachers': ["GUILHERME LUIZ DIAS"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '2.6', 'teachers': ["ANDRE GUSTAVO FELTES"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '2.7', 'teachers': ["EDGAR DIAS SANTANA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '2.8', 'teachers': ["ELIETE APARECIDA KOVALHUK"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '2.9', 'teachers': ["EMANUELE SIQUEIRA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '2.10', 'teachers': ["RODRIGO REDERDE"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '2.11', 'teachers': ["FERNANDA DA SILVA SOARES (CONV)"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '3.1', 'teachers': ["FERNANDO ZAMONER"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '3.2', 'teachers': ["ALECIANE ROBERTA DE OLIVEIRA E SILVA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '3.3', 'teachers': ["ALECIANE ROBERTA DE OLIVEIRA E SILVA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '3.4', 'teachers': ["MELINA SCHENEIDER BASTOS"], 'cohorts': 'DEL'},
    {'code': '3.4', 'teachers': ["MELINA SCHENEIDER BASTOS"], 'cohorts': 'APJ04'},
    {'code': '3.4', 'teachers': ["MARCO AURELIO MOURA DE REZENDE"], 'cohorts': 'APJ05'},
    {'code': '3.4', 'teachers': ["MARCO AURELIO MOURA DE REZENDE"], 'cohorts': 'APJ06'},
    {'code': '3.4P', 'teachers': ["JULIO CESAR NOGUEIRA"], 'cohorts': 'PAP'},
    {'code': '3.5', 'teachers': ["JONATHA ARUS CUNHA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '3.6', 'teachers': ["THIAGO PEREIRA LIMA", "IVO VOURVUPULOS VIANA", "MARISSÔNIA BORTOLOTO"], 'cohorts': 'DEL'},
    {'code': '3.6', 'teachers': ["JONATHA ARUS CUNHA", "SERGIO FERNANDO FERREIRA DE LIMA", "MARISSÔNIA BORTOLOTO"], 'cohorts': 'APJ04'},
    {'code': '3.6', 'teachers': ["JONATHA ARUS CUNHA", "SERGIO FERNANDO FERREIRA DE LIMA", "REBECA MAYER DOS SANTOS"], 'cohorts': 'APJ05'},
    {'code': '3.6', 'teachers': ["REBECA MAYER DOS SANTOS", "VICTOR DAHER RODRIGUES DOS SANTOS"], 'cohorts': 'APJ06'},
    {'code': '3.7', 'teachers': ["RAFAEL VILLANI"], 'cohorts': 'DEL+APJ'},
    {'code': '3.8', 'teachers': ["RAPHAEL DE ASSUMPÇÃO JAMIELNIAK"], 'cohorts': 'DEL+APJ'},
    {'code': '3.9', 'teachers': ["ADRIANO PEREIRA ADURA"], 'cohorts': 'DEL+APJ'},
    {'code': '3.10', 'teachers': ["PAULO MURILO DIAZ BORGES"], 'cohorts': 'DEL+APJ'},
    {'code': '4.1', 'teachers': ["SILVIO JACOB ROCKEMBACH"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.2', 'teachers': ["RENAN BARBOSA LOPES FERREIRA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.3', 'teachers': ["VALDERES LUIZ SCALCO"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.4', 'teachers': ["TRISTÃO ANTÔNIO BORBOREMA DE CARVALHO"], 'cohorts': 'DEL'},
    {'code': '4.4', 'teachers': ["DANIELA CORREA ANTUNES ANDRADE"], 'cohorts': 'APJ04'},
    {'code': '4.4', 'teachers': ["DANIELA CORREA ANTUNES ANDRADE"], 'cohorts': 'APJ05'},
    {'code': '4.4', 'teachers': ["DANIELA CORREA ANTUNES ANDRADE"], 'cohorts': 'APJ06'},
    {'code': '4.4P', 'teachers': ["DANIELA CORREA ANTUNES ANDRADE"], 'cohorts': 'PAP'},
    {'code': '4.5', 'teachers': ["VALDERES LUIZ SCALCO"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.6', 'teachers': ["JOÃO MÁRIO DE GOES"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.6', 'teachers': ["RENATA MAGALHÃES BOHRER"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.7', 'teachers': ["RENAN BARBOSA LOPES FERREIRA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.8', 'teachers': ["JOÃO PAULO CORREA PINHEIRO"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.9', 'teachers': ["ALEXANDRE RORATO"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.10', 'teachers': ["GALMIRETE EGIDIO DA SILVA TOPAN"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.11', 'teachers': ["MARCUS VINICIUS DA COSTA MICHELOTTO"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.12', 'teachers': ["MARCELO LEMOS DE OLIVEIRA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.13', 'teachers': ["RAFAEL BACELAR DE SOUZA "], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.13', 'teachers': ["KAREN GIANE"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.1', 'teachers': ["JORGE AURELIO PERITO DE BEM  (POL. CIENT)"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.2', 'teachers': ["RODRIGO J. DOS SANTOS", "GABRIEL MIQUELETTO", "NOELI ERTHAL", "RUDSTON"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.3', 'teachers': ["RODRIGO J. DOS SANTOS", "GABRIEL MIQUELETTO", "NOELI ERTHAL"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.4', 'teachers': ["RODRIGO J. DOS SANTOS", "GABRIEL MIQUELETTO", "NOELI ERTHAL"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.5', 'teachers': ["ADRIANO CHOHFI", "NOELI ERTHAL", "LAURENCE PAZ DE CARVALHO"], 'cohorts': 'DEL+PAP'},
    {'code': '5.5', 'teachers': ["RAFAEL MARCHINI", "ANDREANO MONTEIRO COSTA DE SOUZA", "ALEXANDRE GERALDI DA ROSA"], 'cohorts': 'APJ04'},
    {'code': '5.5', 'teachers': ["RODRIGO JOSÉ DOS SANTOS", "FABRICIO CESAR COCHITO", "GABRIEL FRANCISCO MIQUELETTO"], 'cohorts': 'APJ05'},
    {'code': '5.5', 'teachers': ["JOHNANDERSON STEFANI BATISTA", "FELIPE LUIS FRANCO", "JOÃO PEDRO DUTRA FILHO"], 'cohorts': 'APJ06'},
    {'code': '5.6', 'teachers': ["THIAGO DA SILVA TEIXEIRA", "RAPHAEL LUIS SOUZA DE PAULA"], 'cohorts': 'DEL+PAP'},
    {'code': '5.6', 'teachers': ["ANDREANO MONTEIRO COSTA DE SOUZA", "RAFAEL MARCHINI"], 'cohorts': 'APJ04'},
    {'code': '5.6', 'teachers': ["LAURENCE PAZ DE CARVALHO", "FELIPE LUIS FRANCO"], 'cohorts': 'APJ05'},
    {'code': '5.6', 'teachers': ["RAPHAEL LUIS SOUZA DE PAULA", "JOHNANDERSON STEFANI BATISTA"], 'cohorts': 'APJ06'},
    {'code': '5.7', 'teachers': ["CRISTIANO AUGUSTO QUINTAS DOS SANTOS"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.8', 'teachers': ["GILSON ANDRE ACOSTA DE JESUS", "NIKOLAS CABRAL DOS SANTOS"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.9', 'teachers': ["ERICA BEATRIZ FRANCO MARTINS", "RAFAEL ANTONIO CORDEIRO DE SOUZA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.10', 'teachers': ["GILSON ANDRE ACOSTA DE JESUS"], 'cohorts': 'DEL+PAP'},
    {'code': '5.10', 'teachers': ["GILSON ANDRE ACOSTA DE JESUS"], 'cohorts': 'APJ04'},
    {'code': '5.10', 'teachers': ["NORMA VOLPATO"], 'cohorts': 'APJ05'},
    {'code': '5.10', 'teachers': ["NORMA VOLPATO"], 'cohorts': 'APJ06'},
    {'code': '5.11', 'teachers': ["THIAGO DA SILVA TEIXEIRA", "RAPHAEL LUIS SOUZA DE PAULA"], 'cohorts': 'DEL+PAP'},
    {'code': '5.11', 'teachers': ["RAPHAEL LUIS SOUZA DE PAULA", "BRUNO MARIANO E SILVA"], 'cohorts': 'APJ04'},
    {'code': '5.11', 'teachers': ["MARCO AURELIO MOCELIN", "GILSON ANDRE ACOSTA DE JESUS"], 'cohorts': 'APJ05'},
    {'code': '5.11', 'teachers': ["DAVID MALHEIRO FADUL", "RAFAEL GAIO"], 'cohorts': 'APJ06'},
    {'code': '5.12', 'teachers': ["JOÃO CARLOS JAKUBIU"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.13', 'teachers': ["CLÁUDIO MARQUES"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.14', 'teachers': ["CRISTIANO AUGUSTO QUINTAS DOS SANTOS"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.15', 'teachers': ["DUCCIO ALFREDO MATUELLA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.16', 'teachers': ["SEBASTIÃO DE PAULA PINTO JÚNIOR", "RODRIGO JOSÉ DOS SANTOS"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.1', 'teachers': ["VYCTOR HUGO GUAITA GROTTI"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.2', 'teachers': ["VYCTOR HUGO GUAITA GROTTI"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.3', 'teachers': ["DAVID MALHEIRO FADUL"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.4', 'teachers': ["ELTER TAETS GARCIA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.5', 'teachers': ["ELTER TAETS GARCIA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.6', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.7', 'teachers': ["VINICIUS AUGUSTUS DE CARVALHO"], 'cohorts': 'DEL'},
    {'code': '6.7', 'teachers': ["DAVID MALHEIRO FADUL"], 'cohorts': 'PAP+APJ'},
    {'code': '6.8', 'teachers': ["RENAN BARBOSA LOPES FERREIRA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.9', 'teachers': ["FLAVIO BALAN"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.10', 'teachers': ["DIOGO CORREA DE OLIVEIRA REIS"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.11', 'teachers': ["CLAUDIA MARTINS", "PATRICIA COCCIA", "URSULA CORREA MANENTI", "MONICA GOMES BOECHAT"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.12', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.13', 'teachers': ["SHEILA M. SCHNEIDER", "DAVID FADUL", "ANDRÉ CANÇADO"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.14', 'teachers': ["DAVID FADUL", "URSULA CORREA MANENTI", "MONICA GOMES BOECHAT"], 'cohorts': 'DEL'},
    {'code': '6.14', 'teachers': ["CLAUDIA MARTINS", "LUCIANE GROCHOCKI"], 'cohorts': 'APJ04'},
    {'code': '6.14', 'teachers': ["PATRICIA COCCIA", "ANDRE CANÇADO"], 'cohorts': 'APJ05'},
    {'code': '6.14', 'teachers': ["SHEILA M. SCHNEIDER", "NOELI ERTHAL"], 'cohorts': 'APJ06'},
    {'code': '6.14p', 'teachers': ["DAVID FADUL", "URSULA CORREA MANENTI", "MONICA GOMES BOECHAT"], 'cohorts': 'PAP'},
   	
]
