teacher_list = [
   {'code': '1.1P', 'teachers': ["VINICIUS AUGUSTUS DE CARVALHO"], 'cohorts': 'PAP'},
   {'code': '1.6', 'teachers': ["RAFAEL BACELAR DE SOUZA"], 'cohorts': 'APJ05'},
   {'code': '1.11', 'teachers': ["ADRIANO CHOHFI"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '1.17', 'teachers': ["FLAVIO ADRIANO BALAN", "GERSON FAUSTINO ROSA", "RODRIGO REDERDE"], 'cohorts': 'DEL+APJ'},

   {'code': '4.2', 'teachers': ["RENAN BARBOSA LOPES FERREIRA"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '4.7', 'teachers': ["RENAN BARBOSA LOPES FERREIRA"], 'cohorts': 'DEL+PAP+APJ'},

   {'code': '5.2', 'teachers': ["RODRIGO J. DOS SANTOS", "GABRIEL MIQUELETTO", "NOELI ERTHAL DA SILVA FERNANDES", "RUDSTON RAMOS"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '5.3', 'teachers': ["RODRIGO J. DOS SANTOS", "GABRIEL MIQUELETTO", "NOELI ERTHAL DA SILVA FERNANDES"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '5.4', 'teachers': ["RODRIGO J. DOS SANTOS", "GABRIEL MIQUELETTO", "NOELI ERTHAL DA SILVA FERNANDES"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '5.5', 'teachers': ["FABRICIO CESAR COCHITO", "FELIPE LUIS FRANCO"], 'cohorts': 'APJ06'}, 
   {'code': '5.5', 'teachers': ["RODRIGO J. DOS SANTOS", "NOELI ERTHAL DA SILVA FERNANDES", "DUCCIO ALFREDO MATUELLA"], 'cohorts': 'APJ05'},
   {'code': '5.5', 'teachers': ["GABRIEL MIQUELETTO"], 'cohorts': 'APJ04'},
   {'code': '5.5', 'teachers': ["ADRIANO CHOHFI", "SEBASTIÃO DE PAULA PINTO JUNIOR"], 'cohorts': 'DEL+PAP'},
   {'code': '5.6', 'teachers': ["FELIPE LUIS FRANCO"], 'cohorts': 'APJ05'},
   {'code': '5.11', 'teachers': ["DAVID FADUL"], 'cohorts': 'APJ06'},
   
   {'code': '6.3', 'teachers': ["DAVID FADUL"], 'cohorts': 'DEL+PAP+APJ'},	
   {'code': '6.4', 'teachers': ["ELTER TAETS GARCIA"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '6.7', 'teachers': ["DAVID FADUL"], 'cohorts': 'PAP+APJ'},
   {'code': '6.7', 'teachers': ["VINICIUS AUGUSTUS DE CARVALHO"], 'cohorts': 'DEL'},
   {'code': '6.8', 'teachers': ["RENAN BARBOSA LOPES FERREIRA"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '6.9', 'teachers': ["FLAVIO ADRIANO BALAN"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '6.13', 'teachers': ["SHEILA M. SCHNEIDER", "DAVID FADUL", "ANDRE DUARTE"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '6.14', 'teachers': ["SHEILA M. SCHNEIDER", "NOELI ERTHAL DA SILVA FERNANDES", ""], 'cohorts': 'APJ06'},
   {'code': '6.14', 'teachers': ["ANDRE DUARTE", "FABRICIO EMMERICH"], 'cohorts': 'APJ05'},   
   {'code': '6.14', 'teachers': ["VYCTOR HUGO GUAITA GROTTI", "URSULA CORREA MANENTI", "MONICA GOMES BOECHAT"], 'cohorts': 'DEL'},
   {'code': '6.14', 'teachers': ["VYCTOR HUGO GUAITA GROTTI", "URSULA CORREA MANENTI", "MONICA GOMES BOECHAT"], 'cohorts': 'PAP'},
   {'code': '6.14', 'teachers': ["CLAUDIA MARTINS"], 'cohorts': 'APJ04'},
   

   {'code': '6.5', 'teachers': ["ELTER TAETS GARCIA"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '6.1', 'teachers': ["VYCTOR HUGO GUAITA GROTTI"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '6.2', 'teachers': ["VYCTOR HUGO GUAITA GROTTI"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '5.7', 'teachers': ["CRISTIANO AUGUSTO QUINTAS DOS SANTOS"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '5.14', 'teachers': ["CRISTIANO AUGUSTO QUINTAS DOS SANTOS"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '5.13', 'teachers': ["CLAUDIO MARQUES"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '2.4', 'teachers': ["CLAUDIO MARQUES"], 'cohorts': 'APJ04'},
   {'code': '2.4', 'teachers': ["CLAUDIO MARQUES"], 'cohorts': 'PAP'},
   {'code': '2.4', 'teachers': ["CLAUDIO MARQUES"], 'cohorts': 'DEL'},
   {'code': '5.6', 'teachers': ["THIAGO DA SILVA TEIXEIRA"], 'cohorts': 'DEL+PAP'},
   {'code': '5.11', 'teachers': ["THIAGO DA SILVA TEIXEIRA"], 'cohorts': 'DEL+PAP'},
   {'code': '5.8', 'teachers': ["GILSON ANDRE ACOSTA DE JESUS", "NIKOLAS CABRAL DOS SANTOS"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '5.10', 'teachers': ["GILSON ANDRE ACOSTA DE JESUS"], 'cohorts': 'DEL+PAP'},
   {'code': '5.5', 'teachers': ["FELIPE LUIS FRANCO"], 'cohorts': 'APJ06'},
   {'code': '5.6', 'teachers': ["FELIPE LUIS FRANCO"], 'cohorts': 'APJ05'},
   {'code': '5.2', 'teachers': ["RODRIGO J. DOS SANTOS", "RUDSTON RAMOS"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '5.3', 'teachers': ["RODRIGO J. DOS SANTOS"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '5.4', 'teachers': ["RODRIGO J. DOS SANTOS"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '1.6', 'teachers': ["RAFAEL BACELAR DE SOUZA"], 'cohorts': 'APJ06'},
   {'code': '4.13', 'teachers': ["RAFAEL BACELAR DE SOUZA "], 'cohorts': 'DEL'},
   {'code': '4.13', 'teachers': ["RAFAEL BACELAR DE SOUZA "], 'cohorts': 'PAP'},
   {'code': '4.13', 'teachers': ["RAFAEL BACELAR DE SOUZA "], 'cohorts': 'APJ04'},
   {'code': '4.9', 'teachers': ["ALEXANDRE RORATO"], 'cohorts': 'DEL'},
   {'code': '4.9', 'teachers': ["ALEXANDRE RORATO"], 'cohorts': 'APJ04'},
   {'code': '4.9', 'teachers': ["ALEXANDRE RORATO"], 'cohorts': 'PAP'},
   {'code': '3.3', 'teachers': ["JOÃO PAULO CORREA PINHEIRO"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '4.8', 'teachers': ["JOÃO PAULO CORREA PINHEIRO"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '4.3', 'teachers': ["VALDERES LUIZ SCALCO"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '4.5', 'teachers': ["VALDERES LUIZ SCALCO"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '3.10', 'teachers': ["PAULO MURILO DIAZ BORGES"], 'cohorts': 'DEL+APJ'},
   {'code': '1.18', 'teachers': ["PAULO MURILO DIAZ BORGES"], 'cohorts': 'APJ05'},
   {'code': '1.18', 'teachers': ["PAULO MURILO DIAZ BORGES"], 'cohorts': 'APJ06'},
   {'code': '1.5', 'teachers': ["ADRIANO PEREIRA ADURA"], 'cohorts': 'APJ05'},
   {'code': '1.5', 'teachers': ["ADRIANO PEREIRA ADURA"], 'cohorts': 'APJ06'},
   {'code': '1.5P', 'teachers': ["ADRIANO PEREIRA ADURA"], 'cohorts': 'PAP'},
   {'code': '1.18', 'teachers': ["ADRIANO PEREIRA ADURA"], 'cohorts': 'DEL'},
   {'code': '1.18', 'teachers': ["ADRIANO PEREIRA ADURA"], 'cohorts': 'APJ04'},
   {'code': '1.5', 'teachers': ["IVO VOURVUPULOS VIANA"], 'cohorts': 'DEL'},
   {'code': '1.5', 'teachers': ["IVO VOURVUPULOS VIANA"], 'cohorts': 'APJ04'},
   {'code': '3.5', 'teachers': ["JONATHA ARUS CUNHA"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '3.6', 'teachers': ["JONATHA ARUS CUNHA"], 'cohorts': 'APJ04'},
   {'code': '3.6', 'teachers': ["REBECA MAYER DOS SANTOS", "THIAGO PEREIRA LIMA", "IVO VOURVUPULOS VIANA"], 'cohorts': 'APJ06'},
   {'code': '1.9', 'teachers': ["FERNANDO ZAMONER"], 'cohorts': 'APJ05'},
   {'code': '1.9', 'teachers': ["FERNANDO ZAMONER"], 'cohorts': 'APJ06'},
   {'code': '3.1', 'teachers': ["FERNANDO ZAMONER"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '1.17', 'teachers': [ "GERSON FAUSTINO ROSA", "RODRIGO REDERDE"], 'cohorts': 'DEL+APJ'},
   {'code': '2.10', 'teachers': ["RODRIGO REDERDE"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '2.3', 'teachers': ["GERSON FAUSTINO ROSA"], 'cohorts': 'APJ05'},
   {'code': '2.3', 'teachers': ["GERSON FAUSTINO ROSA"], 'cohorts': 'APJ06'},
   {'code': '1.1', 'teachers': ["SILAS ROQUE DOS SANTOS"], 'cohorts': 'APJ05'},
   {'code': '1.1', 'teachers': ["SILAS ROQUE DOS SANTOS"], 'cohorts': 'APJ06'},
   {'code': '2.3', 'teachers': ["SILAS ROQUE DOS SANTOS"], 'cohorts': 'DEL'},
   {'code': '2.3', 'teachers': ["SILAS ROQUE DOS SANTOS"], 'cohorts': 'APJ04'},
   {'code': '2.6', 'teachers': ["ANDRE GUSTAVO FELTES"], 'cohorts': 'DEL+PAP+APJ'},
   {'code': '1.3', 'teachers': ["ANDRE GUSTAVO FELTES"], 'cohorts': 'DEL+APJ'},
   {'code': '1.1', 'teachers': ["ANNA KARYNE TURBAY PALODETTO"], 'cohorts': 'DEL'},
   {'code': '1.1', 'teachers': ["ANNA KARYNE TURBAY PALODETTO"], 'cohorts': 'APJ04'},
   {'code': '1.9', 'teachers': ["ANNA KARYNE TURBAY PALODETTO"], 'cohorts': 'DEL'},
   {'code': '1.9', 'teachers': ["ANNA KARYNE TURBAY PALODETTO"], 'cohorts': 'APJ04'},
   {'code': '1.9P', 'teachers': ["ANNA KARYNE TURBAY PALODETTO"], 'cohorts': 'PAP'},
   {'code': '2.2', 'teachers': ["ANNA KARYNE TURBAY PALODETTO"], 'cohorts': 'DEL+APJ'},
   {'code': '1.25P', 'teachers': ["AMANDA RODRIGUES DE MELLO"], 'cohorts': 'PAP'},
   {'code': '1.23P', 'teachers': ["AMANDA RODRIGUES DE MELLO"], 'cohorts': 'PAP'},
   {'code': '1.17P', 'teachers': ["JULIANA VILELA DE BARROS"], 'cohorts': 'PAP'},
   {'code': '1.18P', 'teachers': ["JULIANA VILELA DE BARROS"], 'cohorts': 'PAP'},
   {'code': '1.11P', 'teachers': ["ANA FLAVIA FRIZZO"], 'cohorts': 'PAP'},
   {'code': '1.12P', 'teachers': ["ANA FLAVIA FRIZZO"], 'cohorts': 'PAP'},
   {'code': '1.7', 'teachers': ["ALESSANDRO ROBERTO LUZ"], 'cohorts': 'DEL+APJ'},
   
   
   
   
   
   
   
   
   
]
