teacher_list = [
    {'code': '1.1', 'teachers': [""], 'cohorts': 'DEL'},
    {'code': '1.1', 'teachers': [""], 'cohorts': 'APJ04'},
    {'code': '1.1', 'teachers': [""], 'cohorts': 'APJ05'},
    {'code': '1.1', 'teachers': [""], 'cohorts': 'APJ06'},
    {'code': '1.1P', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '1.2', 'teachers': ["JOSE BARRETO DE MACEDO JUNIOR"], 'cohorts': 'DEL+APJ'}, 
    {'code': '1.2P', 'teachers': ["JOSE BARRETO DE MACEDO JUNIOR"], 'cohorts': 'PAP'},   
    {'code': '1.3', 'teachers': [""], 'cohorts': 'DEL+APJ'},
    {'code': '1.3P', 'teachers': ["MARCELO MAGALHÃES PEREIRA"], 'cohorts': 'PAP'},
    {'code': '1.4', 'teachers': ["ANA CRISTINA FERREIRA"], 'cohorts': 'DEL'},
    {'code': '1.4', 'teachers': ["ANA CRISTINA FERREIRA"], 'cohorts': 'APJ04'},
    {'code': '1.4', 'teachers': ["RAFAEL LUCAS PIRES"], 'cohorts': 'APJ05'},
    {'code': '1.4', 'teachers': ["MARIEL STEDILE TORRES"], 'cohorts': 'APJ06'},
    {'code': '1.4P', 'teachers': ["MARILENE LIMA CONSTANTINO DE ALMEIDA"], 'cohorts': 'PAP'},
    {'code': '1.5', 'teachers': [""], 'cohorts': 'DEL'},
    {'code': '1.5', 'teachers': [""], 'cohorts': 'APJ04'},
    {'code': '1.5', 'teachers': [""], 'cohorts': 'APJ05'},
    {'code': '1.5', 'teachers': [""], 'cohorts': 'APJ06'},
    {'code': '1.5P', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '1.6', 'teachers': ["LEANDRO FARNESE TEIXEIRA"], 'cohorts': 'DEL'},
    {'code': '1.6', 'teachers': ["LEANDRO FARNESE TEIXEIRA"], 'cohorts': 'APJ04'},
    {'code': '1.6', 'teachers': [""], 'cohorts': 'APJ05'},
    {'code': '1.6', 'teachers': [""], 'cohorts': 'APJ06'},  
    {'code': '1.7', 'teachers': [""], 'cohorts': 'DEL+APJ'},
    {'code': '1.9', 'teachers': [""], 'cohorts': 'DEL'},
    {'code': '1.9', 'teachers': [""], 'cohorts': 'APJ04'},
    {'code': '1.9', 'teachers': [""], 'cohorts': 'APJ05'},
    {'code': '1.9', 'teachers': [""], 'cohorts': 'APJ06'},
    {'code': '1.9P', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '1.10', 'teachers': ["EDUARDO BERGMANN MOURA"], 'cohorts': 'DEL+APJ'},
    {'code': '1.11', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '1.12', 'teachers': ["THAYSE CAMPOS MILESKI"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '1.13', 'teachers': ["ROSANA CLAUDIA BOTELHO"], 'cohorts': 'DEL'},
    {'code': '1.13', 'teachers': ["GIORGLLI SOARES PAIN"], 'cohorts': 'APJ04'},
    {'code': '1.13', 'teachers': ["GIORGLLI SOARES PAIN"], 'cohorts': 'APJ05'},
    {'code': '1.13', 'teachers': ["DANIEL LUIZ GODOY DALACQUA"], 'cohorts': 'APJ06'},
    {'code': '1.14', 'teachers': ["LUIZ RAFAEL JUNTA FERRO"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '1.15', 'teachers': ["CARLOS EDUARDO DE ARRUDA SILVEIRA"], 'cohorts': 'DEL+APJ'},
    {'code': '1.16', 'teachers': ["LUIZ RODRIGO GROCHOCKI"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '1.17', 'teachers': [ ""], 'cohorts': 'DEL+APJ'},
    {'code': '1.18', 'teachers': [""], 'cohorts': 'DEL'},
    {'code': '1.18', 'teachers': [""], 'cohorts': 'APJ04'},
    {'code': '1.18', 'teachers': [""], 'cohorts': 'APJ05'},
    {'code': '1.18', 'teachers': [""], 'cohorts': 'APJ06'},
    {'code': '1.11P', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '1.12P', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '1.13P', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '1.14P', 'teachers': ["ALLAN SIMAS DE ALBUQUERQUE"], 'cohorts': 'PAP'},
    {'code': '1.15P', 'teachers': ["JULIANA L. ZEIDAN"], 'cohorts': 'PAP'},
    {'code': '1.16P', 'teachers': ["RODRIGO BERTUOL"], 'cohorts': 'PAP'},
    {'code': '1.17P', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '1.18P', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '1.19P', 'teachers': ["ALINE GRAZIELE FRIZZO"], 'cohorts': 'PAP'},
    {'code': '1.20P', 'teachers': ["KAROL KASUKO ARAKE FRAGOSO PIRES"], 'cohorts': 'PAP'},
    {'code': '1.21P', 'teachers': ["EDUARDO CEZAR SANTOS"], 'cohorts': 'PAP'},
    {'code': '1.22P', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '1.23P', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '1.24P', 'teachers': ["ELENICE BUNICK DE BRITO"], 'cohorts': 'PAP'},
    {'code': '1.25P', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '2.1', 'teachers': ["SANDRA MARA NEPOMUCENO"], 'cohorts': 'DEL+APJ'},
    {'code': '2.2', 'teachers': [""], 'cohorts': 'DEL+APJ'},
    {'code': '2.3', 'teachers': [""], 'cohorts': 'DEL'},
    {'code': '2.3', 'teachers': [""], 'cohorts': 'APJ04'},
    {'code': '2.3', 'teachers': [""], 'cohorts': 'APJ05'},
    {'code': '2.3', 'teachers': [""], 'cohorts': 'APJ06'},
    {'code': '2.4', 'teachers': [""], 'cohorts': 'APJ04'},
    {'code': '2.4', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '2.4', 'teachers': [""], 'cohorts': 'DEL'},
    {'code': '2.4', 'teachers': ["PAULA BRISOLA"], 'cohorts': 'APJ05'},
    {'code': '2.4', 'teachers': ["PAULA BRISOLA"], 'cohorts': 'APJ06'},
    {'code': '2.5', 'teachers': ["GUILHERME LUIZ DIAS"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '2.6', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '2.7', 'teachers': ["EDGAR DIAS SANTANA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '2.8', 'teachers': ["ELIETE APARECIDA KOVALHUK"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '2.9', 'teachers': ["EMANUELE MARIA DE OLIVEIRA SIQUEIRA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '2.10', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '2.11', 'teachers': ["FERNANDA DA SILVA SOARES"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '3.1', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '3.2', 'teachers': ["ALECIANE ROBERTA DE OLIVEIRA E SILVA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '3.3', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '3.4', 'teachers': ["MELINA SCHENEIDER BASTOS"], 'cohorts': 'DEL'},
    {'code': '3.4', 'teachers': ["MELINA SCHENEIDER BASTOS"], 'cohorts': 'APJ04'},
    {'code': '3.4', 'teachers': ["MARCO AURELIO MOURA DE REZENDE"], 'cohorts': 'APJ05'},
    {'code': '3.4', 'teachers': ["MARCO AURELIO MOURA DE REZENDE"], 'cohorts': 'APJ06'},
    {'code': '3.4P', 'teachers': ["JULIO CESAR NOGUEIRA"], 'cohorts': 'PAP'},
    {'code': '3.5', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '3.6', 'teachers': ["THIAGO PEREIRA LIMA", "SERGIO FERNANDES FERREIRA DE LIMA ", "MARISSÔNIA BORTOLOTO"], 'cohorts': 'DEL'},
    {'code': '3.6', 'teachers': ["THIAGO PEREIRA LIMA", "MARISSÔNIA BORTOLOTO"], 'cohorts': 'APJ04'},
    {'code': '3.6', 'teachers': ["THIAGO PEREIRA LIMA", "VICTOR DAHER RODRIGUES DOS SANTOS ", "REBECA MAYER DOS SANTOS"], 'cohorts': 'APJ05'},
    {'code': '3.6', 'teachers': ["REBECA MAYER DOS SANTOS", "THIAGO PEREIRA LIMA"], 'cohorts': 'APJ06'},
    {'code': '3.7', 'teachers': ["RAFAEL VILANI"], 'cohorts': 'DEL+APJ'},
    {'code': '3.8', 'teachers': ["RAPHAEL DE ASSUMPÇÃO JAMIELNIAK"], 'cohorts': 'DEL+APJ'},
    {'code': '3.9', 'teachers': ["ADRIANO PEREIRA ADURA"], 'cohorts': 'DEL+APJ'},
    {'code': '3.10', 'teachers': [""], 'cohorts': 'DEL+APJ'},
    {'code': '4.1', 'teachers': ["SILVIO JACOB ROCKEMBACH"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.2', 'teachers': ["RENAN BARBOSA LOPES FERREIRA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.3', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.4', 'teachers': ["DANIELA CORREA ANTUNES ANDRADE"], 'cohorts': 'DEL'},
    {'code': '4.4', 'teachers': ["DANIELA CORREA ANTUNES ANDRADE"], 'cohorts': 'APJ04'},
    {'code': '4.4', 'teachers': ["DANIELA CORREA ANTUNES ANDRADE"], 'cohorts': 'APJ05'},
    {'code': '4.4', 'teachers': ["DANIELA CORREA ANTUNES ANDRADE"], 'cohorts': 'APJ06'},
    {'code': '4.4', 'teachers': ["DANIELA CORREA ANTUNES ANDRADE"], 'cohorts': 'PAP'},
    {'code': '4.5', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.6', 'teachers': ["JOÃO MARIO DE GOES"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.6', 'teachers': ["RENATA MAGALHÃES BOHRER"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.7', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.8', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.9', 'teachers': [""], 'cohorts': 'DEL'},
    {'code': '4.9', 'teachers': [""], 'cohorts': 'APJ04'},
    {'code': '4.9', 'teachers': ["THIAGO NOBREGA DE ALMEIDA"], 'cohorts': 'APJ05'},
    {'code': '4.9', 'teachers': ["THIAGO NOBREGA DE ALMEIDA"], 'cohorts': 'APJ06'},
    {'code': '4.9', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '4.10', 'teachers': ["GALMIRETE EGIDIO DA SILVA TOPAN"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.11', 'teachers': ["MARCUS VINICIUS DA COSTA MICHELOTTO"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.12', 'teachers': ["MARCELO LEMOS DE OLIVEIRA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '4.13', 'teachers': [""], 'cohorts': 'DEL'},
    {'code': '4.13', 'teachers': [""], 'cohorts': 'PAP'},
    {'code': '4.13', 'teachers': [""], 'cohorts': 'APJ04'},
    {'code': '4.13', 'teachers': ["KAREN GIANE"], 'cohorts': 'APJ05'},
    {'code': '4.13', 'teachers': ["KAREN GIANE"], 'cohorts': 'APJ06'},
    {'code': '5.1', 'teachers': ["JORGE AURELIO PERITO DE BEM"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.2', 'teachers': ["RUDSTON RAMOS"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.3', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.4', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.5', 'teachers': ["RODRIGO SOLOTORIN"], 'cohorts': 'DEL+PAP'},
    {'code': '5.5', 'teachers': ["RAFAEL MARCHINI", "ANDREANO MONTEIRO COSTA DE SOUZA"], 'cohorts': 'APJ04'},
    {'code': '5.5', 'teachers': [""], 'cohorts': 'APJ05'},
    {'code': '5.5', 'teachers': ["JOÃO PEDRO DUTRA FILHO"], 'cohorts': 'APJ06'},
    {'code': '5.6', 'teachers': ["MARCIO WASKOSKI"], 'cohorts': 'DEL+PAP'},
    {'code': '5.6', 'teachers': ["RODRIGO RODRIGUES DE MORAES", "JOSE AUGUSTO DE OLIVEIRA CARATU"], 'cohorts': 'APJ04'},
    {'code': '5.6', 'teachers': ["LAURENCE PAZ DE CARVALHO"], 'cohorts': 'APJ05'},
    {'code': '5.6', 'teachers': ["RODRIGO BRAGA MICHON", "JOHNANDERSON STEFANI BATISTA"], 'cohorts': 'APJ06'},
    {'code': '5.7', 'teachers': ["CRISTIANO AUGUSTO QUINTAS DOS SANTOS"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.8', 'teachers': ["", "NIKOLAS CABRAL DOS SANTOS"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.9', 'teachers': ["ERICA BEATRIZ FRANCO MARTINS", "RAFAEL ANTONIO CORDEIRO DE SOUZA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.10', 'teachers': [""], 'cohorts': 'DEL+PAP'},
    {'code': '5.10', 'teachers': ["DIEGO GRUBBA SCHITKOVSKI"], 'cohorts': 'APJ04'},
    {'code': '5.10', 'teachers': ["NORMA VOLPATO"], 'cohorts': 'APJ05'},
    {'code': '5.10', 'teachers': ["NORMA VOLPATO"], 'cohorts': 'APJ06'},
    {'code': '5.11', 'teachers': ["RAPHAEL LUIS SOUZA DE PAULA"], 'cohorts': 'DEL+PAP'},
    {'code': '5.11', 'teachers': ["RAPHAEL LUIS SOUZA DE PAULA", "BRUNO MARIANO E SILVA"], 'cohorts': 'APJ04'},
    {'code': '5.11', 'teachers': ["MARCO AURELIO MOCELIN", "ISRAEL PEREIRA DE ALBUQUERQUE"], 'cohorts': 'APJ05'},
    {'code': '5.11', 'teachers': ["RAFAEL GAIO"], 'cohorts': 'APJ06'},
    {'code': '5.12', 'teachers': ["JOÃO CARLOS JAKUBIU"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.13', 'teachers': ["CLAUDIO MARQUES"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.14', 'teachers': ["CRISTIANO AUGUSTO QUINTAS DOS SANTOS"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.16', 'teachers': ["GUILHERME LIMA ABUSSAF DOS SANTOS"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '5.17', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.1', 'teachers': ["VYCTOR HUGO GUAITA GROTTI"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.2', 'teachers': ["VYCTOR HUGO GUAITA GROTTI"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.3', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.4', 'teachers': ["ELTER TAETS GARCIA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.5', 'teachers': ["ELTER TAETS GARCIA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.6', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.7', 'teachers': [""], 'cohorts': 'DEL'},
    {'code': '6.7', 'teachers': [""], 'cohorts': 'PAP+APJ'},
    {'code': '6.8', 'teachers': ["RENAN BARBOSA LOPES FERREIRA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.9', 'teachers': ["FLAVIO ADRIANO BALAN"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.10', 'teachers': ["DIOGO CORREA DE OLIVEIRA REIS"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.12', 'teachers': ["HUDSON LEONCIO TEIXEIRA"], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.13', 'teachers': [""], 'cohorts': 'DEL+PAP+APJ'},
    {'code': '6.14', 'teachers': [""], 'cohorts': 'DEL'},
    {'code': '6.14', 'teachers': ["LUCIANE GROCHOCKI", "MARCELO GOMES DE OLIVEIRA"], 'cohorts': 'APJ04'},
    {'code': '6.14', 'teachers': ["PATRICIA COCCIA"], 'cohorts': 'APJ05'},
    {'code': '6.14', 'teachers': [""], 'cohorts': 'APJ06'},
    {'code': '6.14', 'teachers': ["MONICA GOMES BOECHAT"], 'cohorts': 'PAP'},
]
