"""added is_active to cohorts

Revision ID: d9770fb8cf0b
Revises: 0671b732840b
Create Date: 2024-11-18 15:40:14.919514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9770fb8cf0b'
down_revision: Union[str, None] = '0671b732840b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cohorts', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cohorts', 'is_active')
    # ### end Alembic commands ###
